# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 300efca59377115ef68231fdae215a91d33ed92cc4e8380ecfb6d93f9bda098cebb2174f3a9b0c8697243c7a9e06ca7f745ccc65bcc534a50ad2c8d035f46145

test:
  secret_key_base: ef265393595a65d65a22cd09dd34e184fb2efccd34e06ec5c89379c98756124b27647a8acb7c7ed829b9f57b7e4fd5894021b09d47781ed4ee828e2e4ed00eee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
